
auth_enabled: false

server:
  http_listen_port: 3100
  http_server_read_timeout: 600s
  http_server_write_timeout: 600s
  http_server_idle_timeout: 600s
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600

querier:
  engine:
    max_look_back_period: 0s

limits_config:
  retention_period: 8760h
  max_query_length: 0h
  max_query_parallelism: 10
  max_entries_limit_per_query: 10000
  max_streams_per_user: 10000
  max_global_streams_per_user: 10000
  max_chunks_per_query: 2000000
  max_query_series: 500
  max_query_lookback: 0s
  query_timeout: 5m

query_range:
  align_queries_with_step: true
  cache_results: true
  max_retries: 5
  parallelise_shardable_queries: true
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 200
        ttl: 1h

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /data

ingester:
  chunk_idle_period: 5m
  chunk_block_size: 262144
  chunk_retain_period: 1m
  max_chunk_age: 2h
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

compactor:
  working_directory: /data/compactor
  delete_request_store: s3
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h

schema_config:
  configs:
  - from: 2024-12-22
    store: tsdb
    object_store: s3
    schema: v13
    index:
      prefix: index_
      period: 24h

storage_config:
  aws:
    endpoint: s3-vrc.lac-coloc.fr
    access_key_id: "${AWS_ACCESS_KEY_ID}"
    secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
    bucketnames: k8s1-loki
    region: paris
    s3forcepathstyle: true
  tsdb_shipper:
    active_index_directory: /data/index
    cache_location: /data/index_cache
