apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - secrets.yaml

helmCharts:
  - name: k8s-monitoring
    repo: https://grafana.github.io/helm-charts
    namespace: monitoring
    releaseName: k8s-monitoring
    valuesFile: values.yaml
    version: 2.1.4
    includeCRDs: true
  - name: prometheus-operator-crds
    repo: https://prometheus-community.github.io/helm-charts
    version: 21.0.0
    releaseName: prometheus-operator-crds
    namespace: monitoring
    includeCRDs: true
