apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

helmCharts:
  - name: k8s-monitoring
    repo: https://grafana.github.io/helm-charts
    releaseName: monitoring
    namespace: monitoring
    valuesFile: values.yaml
    version: 3.3.2
    includeCRDs: true
