apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - secrets.yaml

helmCharts:
  - name: k8s-monitoring
    repo: https://grafana.github.io/helm-charts
    namespace: monitoring
    releaseName: k8s-monitoring
    valuesFile: values.yaml
    version: 2.1.4
