cluster:
  name: dorado

destinations:
- name: logs
  type: loki
  url: http://loki.monitoring.svc.cluster.local/loki/api/v1/push
  tenantId: dorado
- name: metrics
  type: prometheus
  tenantId: dorado
  url: http://mimir.monitoring.svc.cluster.local/api/v1/push

clusterMetrics:
  enabled: true
  node-exporter:
    jobLabel: node-exporter
    metricsTuning:
      includeMetrics:
        - node_uname_info
        - node_time_seconds
        - node_disk_io_time_seconds_total
        - node_disk_io_time_weighted_seconds_total
        - node_load1
        - node_vmstat_pgmajfault

clusterEvents:
  enabled: true

podLogs:
  enabled: true

alloy-metrics:
  enabled: true
  enableReporting: false

alloy-singleton:
  enabled: true
  enableReporting: false

alloy-logs:
  enabled: true
  enableReporting: false

annotationAutodiscovery:
  enabled: true
  enableReporting: false

serviceMonitors:
  enabled: true
  namespaces: []
  selector: {}

podMonitors:
  enabled: true
  namespaces: []
  selector: {}

prometheusOperatorObjects:
  enabled: true
