# Désactiver Grafana
grafana:
  enabled: false

# Désactiver Alertmanager
alertmanager:
  enabled: false

# Configuration de Prometheus
prometheus:
  prometheusSpec:
    alertingEndpoints: []
    remoteWrite:
      - url: http://mimir.monitoring.svc.cluster.local/api/v1/push
        headers:
          X-Scope-OrgID: dorado
