apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: ceph-csi-drivers
    repo: https://ceph.github.io/ceph-csi-operator
    version: 1.0.5
    releaseName: ceph-csi-drivers
    namespace: rook-ceph
    valuesFile: values.yaml

commonAnnotations:
  argocd.argoproj.io/sync-options: Prune=false,Delete=false
