apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: domain-locker

images:
  - name: ghcr.io/alafranque/domain-locker
    newTag: latest

resources:
  - secrets.yaml
  - deployment.yaml
  - ingress.yaml
  - service.yaml
