apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wol-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: wol-manager
    creationPolicy: Owner
  dataFrom:
    # TELEGRAM_BOT_TOKEN, ALLOWED_USER_IDS
    - extract:
        key: k8s/dorado/applications/wol-manager
