---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
- statefulset.yaml
- service.yaml
- ingress.yaml
- secret.yaml

configMapGenerator:
- name: mimir-config
  files:
  - mimir.yaml

