apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret
  annotations:
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: authentik-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: k8s/dorado/applications/authentik
---
# basic-auth secret (username/password) for the CNPG role, like immich-db
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-db-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: authentik-db-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: k8s/dorado/applications/authentik-db
---
# same S3 credentials as cluster-1, synced into this namespace for barman backups
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-psql-default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: s3-psql-default
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: k8s/dorado/applications/s3-psql-default
