apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: morphos
    app.kubernetes.io/name: morphos
  name: morphos-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: morphos
      app.kubernetes.io/name: morphos
  template:
    metadata:
      labels:
        app: morphos
        app.kubernetes.io/name: morphos
    spec:
      containers:
      - image: ghcr.io/danvergara/morphos-server:0.6.0
        env:
            - name: MORPHOS_PORT
              value: "8080"
        ports:
          - containerPort: 8080
            name: http
        imagePullPolicy: IfNotPresent
        name: morphos
