---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg-system

helmCharts:
  - namespace: cnpg-system
    name: cloudnative-pg
    releaseName: cnpg
    repo: https://cloudnative-pg.github.io/charts
    includeCRDs: true
    version: 0.24.0

resources:
  - cluster.yaml
  - https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.26/releases/cnpg-1.26.0.yaml
