apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-db-secret
  annotations:
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: grafana-db-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: k8s/dorado/applications/grafana-db
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux-db-secret
  annotations:
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: miniflux-db-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: k8s/dorado/applications/miniflux-db
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-db-secret
  annotations:
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: paperless-db-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: k8s/dorado/applications/paperless-db
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plik-db-secret
  annotations:
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: plik-db-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: k8s/dorado/applications/plik-db
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellystat-db-secret
  annotations:
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: jellystat-db-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: k8s/dorado/applications/jellystat-db
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-psql-default
  annotations:
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: s3-psql-default
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: k8s/dorado/applications/s3-psql-default
