apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring
resources:
- secret.yaml
- service.yaml
- statefulset.yaml
- ingress.yaml
configMapGenerator:
- name: grafana-env
  env: grafana.env
- name: grafana-config
  files:
  - grafana.ini

