---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: velero

helmCharts:
  - namespace: velero
    name: velero
    releaseName: velero
    repo: https://vmware-tanzu.github.io/helm-charts
    includeCRDs: true
    valuesFile: values.yaml
    version: 10.1.1

