apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich

resources:
  - ingress.yaml
  - secrets.yaml
  - pvc.yaml
  - postgresql-immich.yaml

helmCharts:
  - name: immich
    repo: https://immich-app.github.io/immich-charts
    version: 0.9.3
    releaseName: immich
    namespace: immich
    valuesFile: values.yaml


