apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless-ngx

resources:
  - ingress.yaml
  - secrets.yaml

helmCharts:
  - name: paperless-ngx
    repo: https://charts.gabe565.com
    version: 0.24.1
    releaseName: paperless-ngx
    namespace: paperless-ngx
    valuesFile: values.yaml
