apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-secret
  annotations:
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: paperless-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: k8s/dorado/applications/paperless
