controllers:
  jellystat:
    containers:
      app:
        image:
          repository: cyfershepard/jellystat
          tag: 1.1.6
        env:
          TZ: Europe/Paris
        envFrom:
          - secretRef:
              name: jellystat
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: 3000
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 10m
            memory: 250Mi
          limits:
            memory: 1Gi

defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001
    fsGroupChangePolicy: OnRootMismatch

service:
  app:
    controller: jellystat
    ports:
      http:
        port: 3000

persistence:
  config:
    suffix: config
    type: persistentVolumeClaim
    storageClass: ceph-block
    accessMode: ReadWriteOnce
    size: 3Gi
    globalMounts:
      - path: /app/backend/backup-data
  tmpfs:
    type: emptyDir
    advancedMounts:
      jellystat:
        app:
          - path: /tmp
            subPath: tmp
