apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: proxy-protocol
  namespace: envoy-gateway-system
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: one-gateway-for-all
  proxyProtocol:
    # Every client connection is forwarded by HAProxy with PROXY protocol.
    optional: false
