apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: france-only
  namespace: envoy-gateway-system
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: one-gateway-for-all
  authorization:
    defaultAction: Deny
    rules:
      - action: Allow
        principal:
          clientIPGeoLocations:
            - country: FR
      - action: Allow
        principal:
          clientCIDRs:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
