apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: miniflux-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: k8s/dorado/applications/miniflux
