apiVersion: v1
kind: Service
metadata:
  name: bichon
  labels:
    app.kubernetes.io/name: bichon
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: bichon
  ports:
    - name: http
      port: 15630
      targetPort: http
      protocol: TCP
