---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellyfin
  namespace: jellyfin
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: jellyfin.png
    gethomepage.dev/name: Jellyfin
    gethomepage.dev/widget.type: jellyfin
    gethomepage.dev/widget.enableMediaControl: false
    gethomepage.dev/widget.showEpisodeNumber: false
    gethomepage.dev/widget.enableNowPlaying: false
    gethomepage.dev/widget.expandOneStreamToTwoRows: false
    gethomepage.dev/widget.key: '{{HOMEPAGE_VAR_JELLYFIN_API_KEY}}'
    gethomepage.dev/widget.url: http://jellyfin.jellyfin.svc.cluster.local:8096
spec:
  parentRefs:
  - name: one-gateway-for-all
    namespace: envoy-gateway-system
    sectionName: https
  hostnames:
  - jellyfin.lac-coloc.fr
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: jellyfin
      port: 8096
---
# HTTPRoute pour HTTP (redirection 301)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellyfin-http-redirect
  namespace: jellyfin
spec:
  parentRefs:
  - name: one-gateway-for-all
    namespace: envoy-gateway-system
    sectionName: http
  hostnames:
  - jellyfin.lac-coloc.fr
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
