apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-pv
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: 10.240.3.19
    path: /volume1/medias
  mountOptions:
    - nfsvers=4
    - rw
    - noatime
    - timeo=300
    - nolock
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-pvc
  annotations:
    backup.velero.io/backup-volumes-excludes: nfs-media-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 10Ti
