---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets

helmCharts:
  - namespace: external-secrets
    name: external-secrets
    releaseName: external-secrets
    repo: https://charts.external-secrets.io
    includeCRDs: true
    version: v0.17.0
