apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-gpt-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: paperless-gpt-config
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: k8s/dorado/applications/paperless-gpt
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-gpt-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: paperless-gpt-auth
    creationPolicy: Owner
  data:
    - secretKey: .htpasswd
      remoteRef:
        key: k8s/dorado/applications/paperless-gpt-auth
        property: users
