apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plik-db-secret
  namespace: plik
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: plik-db-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: k8s/dorado/applications/plik-db
