controllers:
  mealie:
    annotations:
      reloader.stakater.com/auto: "true"

    containers:
      app:
        image:
          repository: ghcr.io/mealie-recipes/mealie
          tag: v3.3.2
        env:
          BASE_URL: https://mealie.lafranque.net
          ALLOW_SIGNUP: true
          API_DOCS: false
          TZ: Europe/Paris
          # Default Values
          WORKERS_PER_CORE: 1
          MAX_WORKERS: 1
          WEB_CONCURRENCY: 1
        envFrom:
          - secretRef:
              name: mealie

        resources:
          requests:
            cpu: 10m
          limits:
            memory: 512M

service:
  app:
    controller: mealie
    ports:
      http:
        port: 9000

persistence:
  config:
    type: persistentVolumeClaim
    storageClass: ceph-block
    accessMode: ReadWriteOnce
    size: 10Gi
    globalMounts:
      - path: /app/data
