apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyseerr

resources:
  - ingress.yaml

helmCharts:
  - name: jellyseerr
    repo: oci://ghcr.io/fallenbagel/jellyseerr/jellyseerr-chart
    namespace: jellyfin
    releaseName: jellyseerr
    valuesFile: values.yaml
    version: 1.9.2
