controllers:
  jellyseerr:
    containers:
      app:
        image:
          repository: fallenbagel/jellyseerr
          tag: 2.7.2
        env:
          TZ: Europe/Paris
          LOG_LEVEL: "info"
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/v1/status
                port: 5055
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 10m
            memory: 250Mi
          limits:
            memory: 1Gi

defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001
    fsGroupChangePolicy: OnRootMismatch

service:
  app:
    controller: jellyseerr
    ports:
      http:
        port: 5055

persistence:
  config:
    suffix: config
    type: persistentVolumeClaim
    storageClass: ceph-block
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /app/config
  tmpfs:
    type: emptyDir
    advancedMounts:
      jellyseerr:
        app:
          - path: /app/config/logs
            subPath: logs
          - path: /tmp
            subPath: tmp
