replicaCount: 1

image:
  registry: ghcr.io
  repository: fallenbagel/jellyseerr
  pullPolicy: Always

# -- Deployment strategy
strategy:
  type: Recreate

# Liveness / Readiness / Startup Probes
probes:
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 30
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  # -- Configure readiness probe
  readinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 30
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  startupProbe: null

serviceAccount:
  create: true
  automount: true

service:
  type: ClusterIP
  port: 80

config:
  persistence:
    size: 5Gi
    accessModes:
      - ReadWriteOnce

ingress:
  enabled: false

resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
