apiVersion: v1
kind: Pod
metadata:
  name: config-fixer
  namespace: medias
spec:
  containers:
    - name: fixer
      image: alpine:latest
      command: ["sleep", "infinity"]
      volumeMounts:
        - mountPath: /config
          name: config-vol
  volumes:
    - name: config-vol
      persistentVolumeClaim:
        claimName: cross-seed-config # ex: cross-seed-config

