apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-system
spec:
  destination:
    namespace: cnpg-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/apps/cloudnative-pg
    repoURL: https://github.com/alcelafranque/k8s-home-cluster.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
