apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-monitoring
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/apps/k8s-monitoring
    repoURL: https://github.com/alcelafranque/k8s-home-cluster.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
