apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 1password.yaml
  - actual.yaml
  - argocd.yaml
  - atuin.yaml
  - authentik.yaml
  - blocky.yaml
  - cert-manager.yaml
  - cillium.yaml
  - cnpg-system.yaml
  - dragonfly.yaml
  - envoy-gateway-system.yaml
  - grafana.yaml
  - homepage.yaml
  - home.yaml
  - immich.yaml
  - k8s-monitoring.yaml
  - librenms.yaml
  - loki.yaml
  - mealie.yaml
  - medias.yaml
  - metric-server.yaml
  - mimir.yaml
  - miniflux.yaml
  - morphos.yaml
  - paperless-ngx.yaml
  - syncthing-relay.yaml
  - velero.yaml
