apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
spec:
  destination:
    namespace: velero
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/apps/velero
    repoURL: https://github.com/alcelafranque/k8s-home-cluster.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
